sudo: required

services:
    - docker

before_install: 
    - docker build -t vida_care_bi_microservices/vida-api-gateway .
    - docker build -t vida_care_bi_microservices/vida-notes-service .
    - docker build -t vida_care_bi_microservices/vida-operations-service .
    - docker build -t vida_care_bi_microservices/vida-users-service .

script:
    - docker run darivo/vida_care_bi_microservices npm test

after_success: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push darivo/vida_care_bi_microservices